#Fri Sep 24 15:12:16 GMT 2021
micronaut:
  application:
    name: comicbook
mongodb:
  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
#kafka:
#  bootstrap:
#    servers: localhost\:9092
db:
  name: 'cbcm'
  collection: 'comicbook'